CREATE TABLE ginga.ginga_obs (
 SEQ_NO INT(10) NOT NULL,
 TARGET_NAME CHAR(80) NOT NULL,
 AVE_ALPHA NUMERIC NOT NULL,
 AVE_DELTA NUMERIC NOT NULL,
 MAX_ALPHA NUMERIC NOT NULL,
 MAX_DELTA NUMERIC NOT NULL,
 MIN_ALPHA NUMERIC NOT NULL,
 MIN_DELTA NUMERIC NOT NULL,
 RIKAKU    NUMERIC NOT NULL,
 STARTTIME DATETIME NOT NULL,
 ENDTIME   DATETIME NOT NULL,
 POINTING  NUMERIC,
 PRIMARY KEY(SEQ_NO)
 )
