DROP TABLE IF EXISTS ginga.GINGA_OBSLOG;
 
CREATE TABLE ginga.GINGA_OBSLOG (
    SEQ_NO INT(10) NOT NULL,
    NUM_PASSES INT NOT NULL,
    TARGET_NAME CHAR(80) NOT NULL,
    AVE_ALPHA FLOAT NOT NULL,
    AVE_DELTA FLOAT NOT NULL,
    MAX_ALPHA FLOAT NOT NULL,
    MAX_DELTA FLOAT NOT NULL,
    MIN_ALPHA FLOAT NOT NULL,
    MIN_DELTA FLOAT NOT NULL,
    FLAG VARCHAR(4) NOT NULL,
    DISTANCE  FLOAT NOT NULL,
    STARTTIME DATETIME NOT NULL,
    ENDTIME   DATETIME NOT NULL,
    POINTING  FLOAT,
    PASS_NAMES VARCHAR(100),
    PRIMARY KEY(SEQ_NO)
) ENGINE=InnoDB;