DROP TABLE IF EXISTS ginga.GINGA_OBS;
 
CREATE TABLE ginga.GINGA_OBS (
    SEQ_NO INT(10) NOT NULL,
    TARGET_NAME CHAR(80) NOT NULL,
    AVE_ALPHA FLOAT NOT NULL,
    AVE_DELTA FLOAT NOT NULL,
    MAX_ALPHA FLOAT NOT NULL,
    MAX_DELTA FLOAT NOT NULL,
    MIN_ALPHA FLOAT NOT NULL,
    MIN_DELTA FLOAT NOT NULL,
    RIKAKU    FLOAT NOT NULL,
    STARTTIME DATETIME NOT NULL,
    ENDTIME   DATETIME NOT NULL,
    POINTING  FLOAT,
    PRIMARY KEY(SEQ_NO)
) ENGINE=InnoDB;
